version: "3"

services:
  
  app:
    build: 
      context: ./app
    container_name: app
    volumes:
      - ./app:/app
    entrypoint: sh -c "npm install && npm start"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASS: root
      DB_NAME: appdb
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0.36-debian
    container_name: database
    volumes:
      - mysql:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
  
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  mysql:
    driver: local